#!/usr/bin/env python3
"""
Environment Setup Script

This script initializes environment variables for the project using dotenv.
It creates a .env file if one doesn't exist and prompts for necessary credentials.
"""

import os
from pathlib import Path


def setup_environment():
    """Initialize environment variables for Earth Engine API."""
    env_path = Path('.env')
    
    print("=" * 60)
    print("Earth Engine API - Environment Setup")
    print("=" * 60)
    print()
    
    if env_path.exists():
        print("✓ .env file already exists")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled. Using existing .env file.")
            return
    
    print("\nPlease provide the following information:")
    print("(Press Enter to skip optional fields)")
    print()
    
    # Collect environment variables
    env_vars = {}
    
    # Google Earth Engine project
    ee_project = input("Google Earth Engine Project ID (required): ").strip()
    if ee_project:
        env_vars['EE_PROJECT'] = ee_project
    
    # Google API credentials (optional)
    google_api_key = input("Google API Key (optional): ").strip()
    if google_api_key:
        env_vars['GOOGLE_API_KEY'] = google_api_key
    
    # Service account credentials path (optional)
    service_account = input("Path to Service Account JSON (optional): ").strip()
    if service_account:
        env_vars['GOOGLE_APPLICATION_CREDENTIALS'] = service_account
    
    # AOI defaults
    aoi_bbox = input("Default AOI bounding box [lon_min,lat_min,lon_max,lat_max] (optional): ").strip()
    if aoi_bbox:
        env_vars['DEFAULT_AOI'] = aoi_bbox
    
    # Date range defaults
    start_date = input("Default start date (YYYY-MM-DD, optional): ").strip()
    if start_date:
        env_vars['DEFAULT_START_DATE'] = start_date
    
    end_date = input("Default end date (YYYY-MM-DD, optional): ").strip()
    if end_date:
        env_vars['DEFAULT_END_DATE'] = end_date
    
    # Cloud cover threshold
    cloud_cover = input("Max cloud cover percentage (0-100, default: 20): ").strip()
    env_vars['MAX_CLOUD_COVER'] = cloud_cover if cloud_cover else '20'
    
    # Write to .env file
    with open(env_path, 'w') as f:
        f.write("# Earth Engine API Configuration\n")
        f.write("# Generated by setup_env.py\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print()
    print("=" * 60)
    print("✓ Environment setup complete!")
    print(f"✓ Configuration saved to {env_path.absolute()}")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Authenticate with Earth Engine: earthengine authenticate")
    print("2. Run the application: python main.py")
    print()


if __name__ == "__main__":
    try:
        setup_environment()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n✗ Error during setup: {e}")
        exit(1)
